version: '3.8'
services:
  redis-db:
    container_name: redis_db
    image: redislabs/redismod #redis/redis-stack #redis/redis-stack-server #redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    #command: redis-server --save 20 1 --loglevel warning
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/rejson.so
        --appendonly yes

    #volumes:
      #- cache:/data
volumes:
  redis-db:
    driver: local

