version: '3.8'

services:
  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
    command: [
      "redis-server", "/usr/local/etc/redis/redis.conf",
      "--loadmodule",
      "/opt/redis-stack/lib/redisearch.so",
      "--loadmodule",
      "/opt/redis-stack/lib/redisgraph.so",
      "--loadmodule",
      "/opt/redis-stack/lib/redistimeseries.so",
      "--loadmodule",
      "/opt/redis-stack/lib/rejson.so",
      "--loadmodule",
      "/opt/redis-stack/lib/redisbloom.so",
      "--loadmodule",
      "/opt/redis-stack/lib/redisgears.so"

    ]
    volumes:
      - ./redis/redis_config_folder:/usr/local/etc/redis/redis.conf

  redis-slave:
    image: "redis/redis-stack"
    ports:
      - "6378:6379"
    command:
      [
        "redis-server", "/usr/local/etc/redis/redis.conf",

        "--loadmodule",
        "/opt/redis-stack/lib/redisearch.so",
        "--loadmodule",
        "/opt/redis-stack/lib/redisgraph.so",
        "--loadmodule",
        "/opt/redis-stack/lib/redistimeseries.so",
        "--loadmodule",
        "/opt/redis-stack/lib/rejson.so",
        "--loadmodule",
        "/opt/redis-stack/lib/redisbloom.so",
        "--loadmodule",
        "/opt/redis-stack/lib/redisgears.so"
      ]
    volumes:
      - ./redis/redis_config_folder:/usr/local/etc/redis/redis.conf
    depends_on:
      - redis