version: '3.8'

services:
  redis:
    image: redislabs/redismod:latest
    ports:
      - "6329:6329"
    command: [
      #"redis-server", "/usr/local/etc/redis/redis.conf",
      "--loadmodule",
      "/usr/lib/redis/modules/redisai.so",
      "--loadmodule",
      "/usr/lib/redis/modules/redisearch.so",
      "--loadmodule",
      "/usr/lib/redis/modules/redisgraph.so",
      "--loadmodule",
      "/usr/lib/redis/modules/redistimeseries.so",
      "--loadmodule",
      "/usr/lib/redis/modules/rejson.so",
      "--loadmodule",
      "/usr/lib/redis/modules/redisbloom.so",
      "--loadmodule",
      "/usr/lib/redis/modules/redisgears.so",
      "Plugin",
      "/var/opt/redislabs/modules/rg/plugin/gears_python.so",
      --port 6379,
    ]
    #volumes:
    #  - ./redis/redis_config_folder:/usr/local/etc/redis/redis.conf

  redis-slave:
    image: redislabs/redismod:latest
    ports:
      - "6380:6379"
    command:
      [
       # "redis-server", "/usr/local/etc/redis/redis.conf",
        "--loadmodule",
        "/usr/lib/redis/modules/redisai.so",
        "--loadmodule",
        "/usr/lib/redis/modules/redisearch.so",
        "--loadmodule",
        "/usr/lib/redis/modules/redisgraph.so",
        "--loadmodule",
        "/usr/lib/redis/modules/redistimeseries.so",
        "--loadmodule",
        "/usr/lib/redis/modules/rejson.so",
        "--loadmodule",
        "/usr/lib/redis/modules/redisbloom.so",
        "--loadmodule",
        "/usr/lib/redis/modules/redisgears.so",
        "Plugin",
        "/var/opt/redislabs/modules/rg/plugin/gears_python.so",
        --REPLICAOF redis 6378,
      ]
    #volumes:
    #  - ./redis/redis_config_folder:/usr/local/etc/redis/redis.conf
    depends_on:
      - redis