version: '3.8'
name: sample-glasfaser
services:
  postgres-db:
    container_name: sample
    image: postgres:14.3-alpine
    restart: always
    command: -c ssl=off
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sample
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"